### ISSUE TITLE
(Enhacement) Metamsk not installed 

### ISSUE THREAD

**Issue by 0xisk** [CryptKeeperZK/crypt-keeper-extension#100]
In case of a browser without Metamask extension installed, CK will keep always loading. 

Expected to stop and to let the user know that it is required to have a wallet (for now only MM). 

![Screenshot_20230219_185741](https://user-images.githubusercontent.com/36774944/219966281-8e61a02b-6410-4ba9-b9ff-154ceea6d0d2.png)

**Comment by 0xmad** [comment]
Fixed
