### ISSUE TITLE
Creates customized eslint rules for checking the debugging global variables

### ISSUE THREAD

**Issue by iskdrews** [CryptKeeperZK/crypt-keeper-extension#112]
Add eslint customized rules for checking the debugging global variables that they are set to false before being pushed. 

https://github.com/CryptKeeperZK/crypt-keeper-extension/blob/0aa9c6b1f2ba9013f3e16a5dbf40b21c391f7602/src/background/backgroundPage.ts#L10

**Comment by iskdrews** [comment]
https://eslint.org/docs/latest/extend/custom-rules

**Comment by 0xmad** [comment]
Maybe we can use env variables it will be easier to achieve.

**Comment by iskdrews** [comment]
@0xmad I tried to use env variables before in the extension, but I still couldn't do it. Let me try do it again.
