### ISSUE TITLE
Define `Code Owners`

### ISSUE THREAD

**Issue by AtHeartEngineer** [CryptKeeperZK/crypt-keeper-extension#296]
The "Main" Branch required "code owners" to approve PRs, blocking one of the devs from being able to merge a PR when another member was out of the office. 

I removed the requirement for "code owners" to approve PRs and left the requirment for 1 other member to sign off on a PR.

Until we establish "code owners" per the [code owners file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners), I think we should leave this off.

**Comment by 0xmad** [comment]
I think it was related to nickname renaming. Now it works as before with this requirement.
