### ISSUE TITLE
Recovery Account from ethereum wallet

### ISSUE THREAD

**Issue by AtHeartEngineer** [CryptKeeperZK/crypt-keeper-extension#35]

**Comment by 0xmad** [comment]
@AtHeartEngineer is it still relevant?
If we want to restore access with ethereum wallet we need to check if this account has created identities in the store.

**Comment by AtHeartEngineer** [comment]
> @AtHeartEngineer is it still relevant?
> If we want to restore access with ethereum wallet we need to check if this account has created identities in the store.

I think this can be closed. I don't think it's relevant anymore. Thanks!
