### ISSUE TITLE
feat: support `RLNProver` in Chrome via Offscreen

### ISSUE THREAD

**Issue by 0xisk** [CryptKeeperZK/crypt-keeper-extension#665]

**Comment by 0xmad** [comment]
@0xisk can we close this issue?

**Comment by 0xmad** [comment]
Done: https://github.com/CryptKeeperZK/crypt-keeper-extension/blob/b973b943306a0c9d04eaceef5d9cced713526150/packages/app/src/offscreen/Offscreen.ts#L84
