### ISSUE TITLE
Release automation

### ISSUE THREAD

**Issue by 0xmad** [CryptKeeperZK/crypt-keeper-extension#675]
- [x] Changelog generation
- [x] Tags
- [x] Github release creation
- [x] Npm publish for provider package
- [x] Chrome store publish
- [x] Firefox store publish
- [x] Build signing and checksum
- [x] Update manifest version automatically
- [x] Add web-ext lint command for each PR

**Comment by 0xisk** [comment]
@0xmad Is there any thing missing in the ticket?

**Comment by 0xmad** [comment]
@0xisk right, we need to test this one.
