### ISSUE TITLE
Account settings "..." ideas

### ISSUE THREAD

**Issue by 0xisk** [CryptKeeperZK/crypt-keeper-extension#8]
- Implementing options in the generated identity accounts. 

![Image](https://user-images.githubusercontent.com/36774944/188387589-434d27af-ec39-461f-833e-85720d0e6efa.png)

**Comment by AtHeartEngineer** [comment]
For now, "delete" is probably the only option we need. In the future it would be good to add permissions settings per account maybe?

**Comment by iskdrews** [comment]
"Rename" would be good option too?

**Comment by AtHeartEngineer** [comment]
Ya that is definitely a good idea

**Comment by iskdrews** [comment]
@AtHeartEngineer Delete, and rename both are supported, do you think we need more options here for now? 


![Image](https://user-images.githubusercontent.com/36774944/192324365-a5f7648b-8e00-4849-bf8e-224df1b009f2.png)

**Comment by AtHeartEngineer** [comment]
I can't think of anything else that's needed, I think that's good for now.

Longer term, it would be good to be able to see which sites are using that account, but that's tied to the permissions system that's mentioned in the backlog. We can worry about that after devcon.
