### ISSUE TITLE
enhacement: shouldn't fire the onRemove event on every closed tab in user browser

### ISSUE THREAD

**Issue by 0xisk** [CryptKeeperZK/crypt-keeper-extension#85]
In the BrowserUtils class, there is always a listener on the browser to the `onRemove` event, it is not working with any tab closed in the browser and that shouldn't be the way it is handled, because each time any tab closed CK extension will be locked. However, that should be fired only in special cases.

**Comment by iskdrews** [comment]
We will not be able to keep the CK popup always open if another window opened like MM window. 
- https://stackoverflow.com/questions/61511542/keep-browser-extension-popup-open-when-a-child-window-is-closed-via-window-clos#comment108818578_61511542
- https://developer.chrome.com/docs/extensions/mv3/faq/#faq-persist-popups

**Comment by iskdrews** [comment]
- Blocked by #140
