### ISSUE TITLE
Make user inputs read only for extension approve modal

### ISSUE THREAD

**Issue by 0xmad** [CryptKeeperZK/crypt-keeper-extension#98]
We need to disable editing inputs for user on extension side.

Questions:

- [x] Do we allow user to change Signal and External nullifier in extension? update: no, we don't.
- [x] Do we allow user to enter random signal value? update: no, it's provided by external party.

![Image](https://user-images.githubusercontent.com/14254374/219422158-89a73c1c-a1de-4426-8c60-3f8b1fb61f4b.png)

**Comment by AtHeartEngineer** [comment]
https://discordapp.com/channels/943612659163602974/1064538262020042802/1075814823612399728

Answered on discord, but the summary is:

The user shouldn't edit these values, they should be provided by the site that is requesting the proof.
